export const HttpErrMsg = {
  BAD_REQUEST: 'BAD_REQUEST',
  DB: {
    DUPLICATE_KEY: 'DB.DUPLICATE_KEY',
    NO_DATA: 'DB.NO_DATA',
    BAD_REQUEST: 'DB.BAD_REQUEST',
    INVALID_OBJECTID: 'DB.INVALID_OBJECTID'
  },
  AUTH: {
    NO_USER: 'AUTH.NO_USER',
    INVALID_PASSWORD: 'AUTH.INVALID_PASSWORD',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED'
  },
  REGISTER: {
    EXIST_TEL: 'REGISTER.EXIST_TEL',
    EXIST_EMAIL: 'REGISTER.EXIST_EMAIL'
  }
};
