export const HttpErrCode = {
  JWT: { NO_TOKEN: 'JWT.NO_TOKEN' },
  LOGIN: {
    NO_USER: 'LOGIN.NO_USER',
    INVALID_PASSWORD: 'LOGIN.INVALID_PASSWORD',
    NOT_AUTHORIZED: 'LOGIN.NOT_AUTHORIZED'
  },
  REGISTER: {
    EXIST_PHONE: 'REGISTER.EXIST_PHONE',
    EXIST_EMAIL: 'REGISTER.EXIST_EMAIL'
  }
};
